# Streamlit Cloud deployment configuration

[global]
developmentMode = false

[server]
runOnSave = false
port = 8501
enableCORS = true
enableXsrfProtection = true
headless = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#2E8B57"
backgroundColor = "#FFFFFF" 
secondaryBackgroundColor = "#F0F8F0"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "viewer"
